---
title: "P1_adapter_ligation"
author: "MS"
date: "16 April 2015"
output: html_document
---

## 3. P1 adapter ligation

#### Materials

Barcoded P1 adapters (IDT) RD_P1_101 to RD_P1_196 (100nM) (Appendix (2, 3 & 5))
	*(Need to check how to prepare them)*  
T4 Quick ligase (NEB #M2200L)   
10x NEBuffer 2 (NEB # B7002S)  
100mM rATP (Promega # E6011)  
Ultrapure dH2O  
PCR block  

#### General

* Ligations will work in any NEB Buffer if rATP is included in the reaction.
* For 400ng DNA, 4uL P1 Adapter (100 nM) is used. 
* The Barcoded P1 adapters have been aliquoted into strip tubes in an order that
permits optimal pooling. The 8-well PCR tubes are then arranged in the format
of a 96-well plate. Appendix 2.

#### Protocol

1. Add 4uL of each P1 adapter to each tube using a 10uL multichannel pipette.
2. Add 6uL of ligation MM to each tube using a 10uL multichannel pipette  


Reagent         | 1 x Reaction | 17 x Reaction
----------------|--------------|--------------
NEB Buffer 2    | 1.0 $\mu$l   | 17.0 $\mu$l
100mM rATP      | 0.6 $\mu$l   | 10.2 $\mu$l
T4 Quick Ligase | 1.0 $\mu$l   | 17.0 $\mu$l
dH20            | 3.4 $\mu$l   | 57.8 $\mu$l
Total           | 6.0 $\mu$l   | 102.0 $\mu$l  

*Again: Add largest volume ( H2O) at last and mix with pipette*

3. Place the strip tubes in a PCR block that has been programmed as follows:
- (XXX program in Kanchon´s lab)
- Reaction volume: 60 $\mu$l 
- **Incubate: 60 min at 22°**
- **Denature: 10 min at 65°**
- **HOLD: 22°**

Samples can be frozen overnight if required.
